{{ config(materialized='table') }}

with Location as (

    select * from {{ ref('Location') }}

),

DATEx as (

    select * from {{ ref('Date') }}

),

COVIDSTATS as (

    select
	DATEx.DATE_SK,
	LOCATION.LOC_SK,
FULL_EXTRACT.NEW_CASES_PER_MILLION,
FULL_EXTRACT.NEW_CASES,
FULL_EXTRACT.GROWTH_FACTOR_OF_NEW_CASES,
FULL_EXTRACT.NEW_DEATHS_PER_MILLION,
FULL_EXTRACT.NEW_DEATHS,
FULL_EXTRACT.GROWTH_FACTOR_OF_NEW_DEATHS,
FULL_EXTRACT.NEW_RECOVERED,
FULL_EXTRACT.NEW_ACTIVE_CASES,
FULL_EXTRACT.TOTAL_CASES_PER_MILLION,
FULL_EXTRACT.TOTAL_CASES,
FULL_EXTRACT.TOTAL_DEATHS_PER_MILLION,
FULL_EXTRACT.TOTAL_DEATHS,
FULL_EXTRACT.CASE_RECOVERED_RATE
    from FULL_EXTRACT
    left join LOCATION ON LOCATION.LOCATION=FULL_EXTRACT.LOCATION 
    LEFT JOIN DATEx ON DATEx.DATE=FULL_EXTRACT.DATE
)

select * from COVIDSTATS 